# Use Python 3 as the base image.
FROM python:3

# Set the working directory.
WORKDIR /app

# Copy the requirements file.
COPY requirements.txt .

# Install dependencies.
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the application code.
COPY . .

# Expose the port the app runs on.
EXPOSE 8000
